spring.application.name=spring-data-jpa-example



spring.datasource.url= jdbc:postgresql://localhost:5432/Star
spring.datasource.username=hardivirani
#spring.datasource.password=""
spring.datasource.driver-class-name=org.postgresql.Driver