spring.application.name=spring-data-jpa-example



spring.datasource.url= jdbc:postgresql://localhost:5432/Star
spring.datasource.username=hardivirani
#spring.datasource.password=""
spring.datasource.driver-class-name=org.postgresql.Driver


# We are telling our hibernate to create a table for us.

#instead of update we are can also write create but for that, whenever the application will start it will keep creating the new table.
spring.jpa.hibernate.ddl-auto=update

#it will show us the query
spring.jpa.show-sql = true

